#!/usr/bin/env bash
apt-get install -y git
dir=$(pwd)
cd /usr/local && curl http://nodejs.org/dist/v0.10.23/node-v0.10.23-linux-x64.tar.gz | tar -xzvf- --strip-components=1
cd "$dir"
npm install --production
npm -g install "git+https://github.com/mmalecki/node-autostart.git#upstart"
autostart service --name santa-hello-world --platform upstart --start "node /root/package/app.js"
